default_language_version:
  python: python3.8
  node: system

repos:
  - repo: https://github.com/PyCQA/isort
    rev: "5.10.1"
    hooks:
      - id: isort
        alias: isort_all
        name: "isort (ote_cli|external|ote_sdk)"
        args: ["--settings", ".isort.cfg"]
        files: '^(ote_cli|external/anomaly|ote_sdk)/.*\.py'
        exclude: "tests/"

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        name: "black (ote_sdk|ote_cli)"
        args: [--line-length, "88"]
        files: '^(ote_sdk|ote_cli)/.*\.py'
      - id: black
        name: "black (rest)"
        args: [--line-length, "120"]
        files: '^external/anomaly/.*\.py'

  - repo: https://github.com/PyCQA/flake8
    rev: "5.0.3"
    hooks:
      - id: flake8
        name: "flake8"
        files: '^(ote_sdk|ote_cli|external/anomaly)/.*\.py'
        args: ["--config", ".flake8", "--max-complexity", "20"]
        exclude: ".*/protobuf"

  # yaml formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        exclude: "external/deep-object-reid"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.971"
    hooks:
      - id: mypy
        alias: mypy
        name: "mypy"
        files: '^(ote_sdk|ote_cli)/.*\.py'
        additional_dependencies:
          [
            numpy==1.19.5,
            types-PyYAML,
            attrs==21.2.*,
            types-requests,
            types-Deprecated,
            types-docutils,
            types_futures,
            types-python-dateutil,
          ]
        exclude: "^external/anomaly/tests"

  - repo: https://github.com/PyCQA/pylint
    rev: "v2.14.5"
    hooks:
      - id: pylint
        name: "pylint"
        files: '^(ote_sdk|ote_cli|external/anomaly)/.*\.py'
        entry: pylint
        language: system
        types: [python]
        args: ["--score=no", "--rcfile=.pylintrc"]
        exclude: "tests"
