# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# SETUP CONFIGURATION.                                                        #
[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# ISORT CONFIGURATION.                                                        #
[tool.isort]
profile = "black"
known_first_party = ["ote_cli", "ote_sdk"]


# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# MYPY CONFIGURATION.                                                         #
[tool.mypy]
python_version = 3.8
ignore_missing_imports = true
show_error_codes = true


# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# PYLINT CONFIGURATION                                                        #
[tool.pylint.master]
fail-under = 10
ignore = "CVS"
ignore-patterns = "^.*test_.*.py"
jobs = 0
limit-inference-results = 100
persistent = "yes"
suggestion-mode = "yes"
unsafe-load-any-extension = "no"

[tool.pylint.messages_control]
disable = [
    "logging-fstring-interpolation",
    "too-few-public-methods",
    "fixme",
    "duplicate-code",
    "raw-checker-failed",
    "bad-inline-option",
    "locally-disabled",
    "file-ignored",
    "suppressed-message",
    "useless-suppression",
    "deprecated-pragma",
    "use-symbolic-message-instead",
    "import-outside-toplevel",
    "arguments-differ",
]
enable = "c-extension-no-member"

[tool.pylint.typecheck]
contextmanager-decorators = "contextlib.contextmanager"
generated-members = ["numpy.*", "torch.*"]
ignore-mixin-members = "yes"
ignore-none = "yes"
ignore-on-opaque-inference = "yes"
ignored-classes = ["optparse.Values", "thread._local", "_thread._local"]
missing-member-hint = "yes"
missing-member-hint-distance = 1
missing-member-max-choices = 1
ignored-modules = [
    "ote_sdk",
    "mmseg",
    "segmentation_tasks",
    "mmdet",
    "detection_tasks",
    "torchreid",
    "torchreid_tasks",
    "cv2",
    "anomalib",
    "pytorch_lightning",
    "torch",
    "addict",
    "compression",
    "openvino",
    "pandas",
]

[tool.pylint.format]
ignore-long-lines = '^\s*(# )?<?https?://\S+>?$'
indent-after-paren = 4
indent-string = '    '
max-line-length = 120
max-module-lines = 1000
single-line-class-stmt = "no"
single-line-if-stmt = "no"

[tool.pylint.similarities]
ignore-comments = "yes"
ignore-docstrings = "yes"
ignore-imports = "no"
min-similarity-lines = 4

[tool.pylint.basic]
docstring-min-length = -1
good-names = [
    "i",
    "j",
    "k",
    "ex",
    "Run",
    "_",
    "x1",
    "x2",
    "y1",
    "y2",
    "x",
    "y",
    "r",
    "id",
    "type",
    "xs",
    "ys",
    "i",
    "p",
    "f",
]

[tool.pylint.imports]
known-third-party = ["enchant", "ote_sdk"]

[tool.pylint.design]
max-args = 7
