model:
  class_path: otx.algo.anomaly.stfpm.STFPM
  init_args:
    input_size:
      - 256
      - 256
    layers: ["layer1", "layer2", "layer3"]
    backbone: "resnet18"

engine:
  task: ANOMALY_CLASSIFICATION
  device: auto

callback_monitor: step

data: ../_base_/data/torchvision_base.yaml
overrides:
  max_epochs: 100
  limit_val_batches: 0
  data:
    task: ANOMALY_CLASSIFICATION
    config:
      data_format: mvtec
      vpm_config:
        use_bbox: True
        use_point: False
      train_subset:
        batch_size: 1
        num_workers: 4
        transforms:
          - class_path: otx.core.data.transform_libs.torchvision.ResizetoLongestEdge
            init_args:
              size: 1024
              antialias: True
          - class_path: otx.core.data.transform_libs.torchvision.PadtoSquare
          - class_path: torchvision.transforms.v2.ToDtype
            init_args:
              dtype: ${as_torch_dtype:torch.float32}
              scale: False
          - class_path: torchvision.transforms.v2.Normalize
            init_args:
              mean: [123.675, 116.28, 103.53]
              std: [58.395, 57.12, 57.375]
      val_subset:
        batch_size: 1
        num_workers: 4
        transforms:
          - class_path: otx.core.data.transform_libs.torchvision.ResizetoLongestEdge
            init_args:
              size: 1024
              antialias: True
          - class_path: otx.core.data.transform_libs.torchvision.PadtoSquare
          - class_path: torchvision.transforms.v2.ToDtype
            init_args:
              dtype: ${as_torch_dtype:torch.float32}
              scale: False
          - class_path: torchvision.transforms.v2.Normalize
            init_args:
              mean: [123.675, 116.28, 103.53]
              std: [58.395, 57.12, 57.375]
      test_subset:
        batch_size: 1
        num_workers: 4
        transforms:
          - class_path: otx.core.data.transform_libs.torchvision.ResizetoLongestEdge
            init_args:
              size: 1024
              antialias: True
          - class_path: otx.core.data.transform_libs.torchvision.PadtoSquare
          - class_path: torchvision.transforms.v2.ToDtype
            init_args:
              dtype: ${as_torch_dtype:torch.float32}
              scale: False
          - class_path: torchvision.transforms.v2.Normalize
            init_args:
              mean: [123.675, 116.28, 103.53]
              std: [58.395, 57.12, 57.375]